repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      # lint
      - id: ruff
        name: ruff-lint
        description: "Run ruff to lint on changed python files"
        entry: ruff check --force-exclude
        language: python
        types: [python]
      # format
      - id: ruff-format
        name: ruff-format
        description: "Run ruff to format on changed python files"
        entry: ruff format .
        language: python
        types: [python]