name: lint

on:
  push:
    paths:
      - "*.py"

jobs:
  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install ruff
        run: pip install ruff
      - name: Run ruff
        run: ruff --format=github .
        continue-on-error: true