name: test

on:
  push:
    paths:
      - "tests/**/*.py"

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install pytest
        run: pip install pytest
      - name: Run pytest
        run: pytest -vs
